In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df.shape

(10000, 14)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [7]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [8]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [9]:
df["Gender"].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [10]:
df.drop(columns=["RowNumber",
                 "CustomerId",
                 "Surname"],
                 inplace=True)

df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
df = pd.get_dummies(
    df,
    columns=["Geography", "Gender"],
    drop_first=True,
    dtype=int
)

df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0

In [12]:
from sklearn.model_selection import train_test_split

X = df.drop(columns= ["Exited"])
y = df["Exited"]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42,
                                                    test_size=0.2)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
import tensorflow

In [17]:
from keras.models import Sequential
from keras.layers import Input, Dense

model = Sequential()
model.add(Input(shape=(11,)))
model.add(Dense(3, activation="sigmoid"))
model.add(Dense(1, activation="sigmoid"))

In [19]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 3)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 40 (160.00 B)

 Trainable params: 40 (160.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.compile(loss="binary_crossentropy",
              optimizer="Adam")

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [30]:
model.fit(
    X_train_scaled,
    y_train,
    epochs=30
)

Epoch 1/30
  1/250 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.3440

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - loss: 0.4571
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - loss: 0.4498
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - loss: 0.4438
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - loss: 0.4392
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step - loss: 0.4356
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 0.4329
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 0.4308
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - loss: 0.4291
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 703us/step - loss: 0.4275
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step - loss: 0.4261
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 736us/step - loss: 0.4246
Epoch 12/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 0.4231
Epoch 13/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 0.4216
Epoch 14/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 676us/step - loss: 0.4202
Epoch 15/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - loss: 0.4188
Epoch 16/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 675us/step - loss: 0.4175
Epoch 17/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - loss: 0.4164
Epoch 18/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step - loss: 0.4154
Epoch 19/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - loss: 0.4144
Epoch 20/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - loss: 0.4136
Epoch 21/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 756us/step - loss: 0.4129
Epoch 22/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - loss: 0.4121
Epoch 23/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - loss: 0.4114
Epoch 24/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - loss: 0.4108
Epoch 25/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 666us/step - loss: 0.4102
Epoch 26/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 674us/step - loss: 0.4095
Epoch 27/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 0.4089
Epoch 28/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 670us/step - loss: 0.4083
Epoch 29/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 711us/step - loss: 0.4077
Epoch 30/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 663us/step - loss: 0.4070

In [31]:
model.layers[1].get_weights()

[array([[ 1.1017054],
        [-2.0041437],
        [ 1.4475453]], dtype=float32),
 array([-1.3431587], dtype=float32)]

In [32]:
model.layers[0].get_weights()

[array([[-0.19897239, -0.03644861, -0.23703048],
        [ 2.1730554 , -0.32310462,  3.5986407 ],
        [-0.0697751 ,  0.1105381 , -0.01472149],
        [-0.2944167 , -0.57217985, -0.04142962],
        [-1.8979019 , -0.28519312,  0.2212607 ],
        [ 0.14837918,  0.03748882,  0.04023561],
        [ 0.17531072,  1.7720268 ,  0.41253948],
        [-0.06538358, -0.14315721, -0.19290249],
        [ 0.253231  , -0.8833947 ,  0.31168324],
        [ 0.13274314, -0.06928818,  0.05662695],
        [-0.09271576,  0.7199088 , -0.10952418]], dtype=float32),
 array([-1.0512886 ,  0.95024884, -0.6689529 ], dtype=float32)]

In [33]:
y_log = model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step

In [34]:
y_pred = np.where(y_log>0.5, 1, 0)

In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,
               y_pred)

0.8315